version: '3.8'

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]

  flaskapp:
    build:
      context: ../src
      dockerfile: ../docker/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    volumes:
      - ../src:/app
    working_dir: /app
    command: ["python3", "run.py"]

volumes:
  redis_data:
